version: '3'

services:
  slim-web:
    build:
      context: .
    container_name: slim-web
    ports:
      - "8081:80"
    depends_on:
      - pgsql
    environment:
      #DB_HOST: pgsql
      #DB_PORT: 5432
      DB_HOST: host.docker.internal
      DB_PORT: 5466
    volumes:
      - .:/var/www/html
  composer:
    image: composer:2.3
    container_name: composer
    command: ["install"]
    working_dir: /var/www/html
    depends_on:
      - slim-web
    volumes:
      - .:/var/www/html
  pgsql:
    image: postgres:9.6.24
    container_name: pgsql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql/tables.sql:/docker-entrypoint-initdb.d/tables.sql 